version: '3.4'

services:
  servicea:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    ports:
       - "6777:80"
  webeditor:
    image: ${DOCKER_REGISTRY-}webeditor
    build:
      context: .
      dockerfile: WebEditor/Dockerfile
    ports:
       - "6778:80"
  serviceb:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    ports:
       - "6779:80"